version: '3'

services:
  springboot:
    image: srikanth6520/spring-mongo
    restart: always # This will be ignored if we deploy in docker swarm
    environment:
    - MONGO_DB_HOSTNAME=mongo
    - MONGO_DB_USERNAME=user
    - MONGO_DB_PASSWORD=password
    ports:
      - 8080:8080
    working_dir: /opt/app
    depends_on:
      - mongo
    networks:
    - amazon
    deploy:  # This will be considered only in docker swarm.
      replicas: 2
      update_config:
        parallelism: 1
        delay: 20s
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5

  mongo:
    image: mongo
    environment:
    - MONGO_INITDB_ROOT_USERNAME=user
    - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongoapp:/data/db
    restart: always
    networks:
    - amazon
    
volumes:
  mongoapp:
    external: true
    
networks:
  amazon:
    external: true
